/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FfButton {
        /**
          * Brand key resolved against the external CSS token contract. This stays open so apps can ship brand overrides outside the component package.
          * @default 'inherit'
         */
        "brand": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "fullWidth": boolean;
        "label"?: string;
        /**
          * @default 'auto'
         */
        "previewState": PreviewState;
        /**
          * Theme key resolved against the external CSS token contract. Consumers can keep the shipped `light` / `dark` values or define their own.
          * @default 'inherit'
         */
        "theme": string;
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
    }
}
declare global {
    interface HTMLFfButtonElement extends Components.FfButton, HTMLStencilElement {
    }
    var HTMLFfButtonElement: {
        prototype: HTMLFfButtonElement;
        new (): HTMLFfButtonElement;
    };
    interface HTMLElementTagNameMap {
        "ff-button": HTMLFfButtonElement;
    }
}
declare namespace LocalJSX {
    interface FfButton {
        /**
          * Brand key resolved against the external CSS token contract. This stays open so apps can ship brand overrides outside the component package.
          * @default 'inherit'
         */
        "brand"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "fullWidth"?: boolean;
        "label"?: string;
        /**
          * @default 'auto'
         */
        "previewState"?: PreviewState;
        /**
          * Theme key resolved against the external CSS token contract. Consumers can keep the shipped `light` / `dark` values or define their own.
          * @default 'inherit'
         */
        "theme"?: string;
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
    }

    interface FfButtonAttributes {
        "theme": string;
        "brand": string;
        "disabled": boolean;
        "type": 'button' | 'submit' | 'reset';
        "fullWidth": boolean;
        "label": string;
        "previewState": PreviewState;
    }

    interface IntrinsicElements {
        "ff-button": Omit<FfButton, keyof FfButtonAttributes> & { [K in keyof FfButton & keyof FfButtonAttributes]?: FfButton[K] } & { [K in keyof FfButton & keyof FfButtonAttributes as `attr:${K}`]?: FfButtonAttributes[K] } & { [K in keyof FfButton & keyof FfButtonAttributes as `prop:${K}`]?: FfButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ff-button": LocalJSX.IntrinsicElements["ff-button"] & JSXBase.HTMLAttributes<HTMLFfButtonElement>;
        }
    }
}
