/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FfDropdownOpenChangeDetail, FfDropdownOption, FfDropdownValueChangeDetail } from "./components/ff-dropdown/ff-dropdown";
export { FfDropdownOpenChangeDetail, FfDropdownOption, FfDropdownValueChangeDetail } from "./components/ff-dropdown/ff-dropdown";
export namespace Components {
    /**
     * Logic-only button primitive shared across every consumer framework.
     * The component intentionally owns only semantic behavior and a stable DOM contract.
     * Visual identity must come from the consuming application's token contract and brand pack.
     */
    interface FfButton {
        /**
          * Disables pointer and keyboard interaction on the native button element.
          * @default false
         */
        "disabled": boolean;
        /**
          * Expands the host to full width without coupling layout rules to a brand theme.
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Provides a simple fallback label when no slotted content is passed.
         */
        "label"?: string;
        /**
          * Mirrors the native button type attribute so forms keep expected behavior.
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
    }
    /**
     * Accessible dropdown primitive that keeps all interaction logic inside Stencil.
     * The component owns keyboard navigation, selection state, focus handling, and the
     * public accessibility contract. Visual identity still comes exclusively from the
     * external token contract and the active brand pack.
     */
    interface FfDropdown {
        /**
          * Disables opening, keyboard navigation, and option selection.
          * @default false
         */
        "disabled": boolean;
        /**
          * Expands the host to the width of its container.
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Visible field label and accessible name for the dropdown trigger.
          * @default 'Select an option'
         */
        "label": string;
        /**
          * Complete option list rendered by the dropdown panel.
          * @default []
         */
        "options": FfDropdownOption[];
        /**
          * Placeholder text shown when no option is currently selected.
          * @default 'Choose an option'
         */
        "placeholder": string;
        /**
          * Currently selected option value. Can be controlled from the consuming app shell.
         */
        "value"?: string;
    }
}
export interface FfDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFfDropdownElement;
}
declare global {
    /**
     * Logic-only button primitive shared across every consumer framework.
     * The component intentionally owns only semantic behavior and a stable DOM contract.
     * Visual identity must come from the consuming application's token contract and brand pack.
     */
    interface HTMLFfButtonElement extends Components.FfButton, HTMLStencilElement {
    }
    var HTMLFfButtonElement: {
        prototype: HTMLFfButtonElement;
        new (): HTMLFfButtonElement;
    };
    interface HTMLFfDropdownElementEventMap {
        "ffValueChange": FfDropdownValueChangeDetail;
        "ffOpenChange": FfDropdownOpenChangeDetail;
    }
    /**
     * Accessible dropdown primitive that keeps all interaction logic inside Stencil.
     * The component owns keyboard navigation, selection state, focus handling, and the
     * public accessibility contract. Visual identity still comes exclusively from the
     * external token contract and the active brand pack.
     */
    interface HTMLFfDropdownElement extends Components.FfDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFfDropdownElementEventMap>(type: K, listener: (this: HTMLFfDropdownElement, ev: FfDropdownCustomEvent<HTMLFfDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFfDropdownElementEventMap>(type: K, listener: (this: HTMLFfDropdownElement, ev: FfDropdownCustomEvent<HTMLFfDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFfDropdownElement: {
        prototype: HTMLFfDropdownElement;
        new (): HTMLFfDropdownElement;
    };
    interface HTMLElementTagNameMap {
        "ff-button": HTMLFfButtonElement;
        "ff-dropdown": HTMLFfDropdownElement;
    }
}
declare namespace LocalJSX {
    /**
     * Logic-only button primitive shared across every consumer framework.
     * The component intentionally owns only semantic behavior and a stable DOM contract.
     * Visual identity must come from the consuming application's token contract and brand pack.
     */
    interface FfButton {
        /**
          * Disables pointer and keyboard interaction on the native button element.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Expands the host to full width without coupling layout rules to a brand theme.
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Provides a simple fallback label when no slotted content is passed.
         */
        "label"?: string;
        /**
          * Mirrors the native button type attribute so forms keep expected behavior.
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
    }
    /**
     * Accessible dropdown primitive that keeps all interaction logic inside Stencil.
     * The component owns keyboard navigation, selection state, focus handling, and the
     * public accessibility contract. Visual identity still comes exclusively from the
     * external token contract and the active brand pack.
     */
    interface FfDropdown {
        /**
          * Disables opening, keyboard navigation, and option selection.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Expands the host to the width of its container.
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Visible field label and accessible name for the dropdown trigger.
          * @default 'Select an option'
         */
        "label"?: string;
        /**
          * Emitted when the dropdown panel opens or closes.
         */
        "onFfOpenChange"?: (event: FfDropdownCustomEvent<FfDropdownOpenChangeDetail>) => void;
        /**
          * Emitted when the selected value changes.
         */
        "onFfValueChange"?: (event: FfDropdownCustomEvent<FfDropdownValueChangeDetail>) => void;
        /**
          * Complete option list rendered by the dropdown panel.
          * @default []
         */
        "options"?: FfDropdownOption[];
        /**
          * Placeholder text shown when no option is currently selected.
          * @default 'Choose an option'
         */
        "placeholder"?: string;
        /**
          * Currently selected option value. Can be controlled from the consuming app shell.
         */
        "value"?: string;
    }

    interface FfButtonAttributes {
        "disabled": boolean;
        "type": 'button' | 'submit' | 'reset';
        "fullWidth": boolean;
        "label": string;
    }
    interface FfDropdownAttributes {
        "label": string;
        "placeholder": string;
        "value": string;
        "disabled": boolean;
        "fullWidth": boolean;
    }

    interface IntrinsicElements {
        "ff-button": Omit<FfButton, keyof FfButtonAttributes> & { [K in keyof FfButton & keyof FfButtonAttributes]?: FfButton[K] } & { [K in keyof FfButton & keyof FfButtonAttributes as `attr:${K}`]?: FfButtonAttributes[K] } & { [K in keyof FfButton & keyof FfButtonAttributes as `prop:${K}`]?: FfButton[K] };
        "ff-dropdown": Omit<FfDropdown, keyof FfDropdownAttributes> & { [K in keyof FfDropdown & keyof FfDropdownAttributes]?: FfDropdown[K] } & { [K in keyof FfDropdown & keyof FfDropdownAttributes as `attr:${K}`]?: FfDropdownAttributes[K] } & { [K in keyof FfDropdown & keyof FfDropdownAttributes as `prop:${K}`]?: FfDropdown[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Logic-only button primitive shared across every consumer framework.
             * The component intentionally owns only semantic behavior and a stable DOM contract.
             * Visual identity must come from the consuming application's token contract and brand pack.
             */
            "ff-button": LocalJSX.IntrinsicElements["ff-button"] & JSXBase.HTMLAttributes<HTMLFfButtonElement>;
            /**
             * Accessible dropdown primitive that keeps all interaction logic inside Stencil.
             * The component owns keyboard navigation, selection state, focus handling, and the
             * public accessibility contract. Visual identity still comes exclusively from the
             * external token contract and the active brand pack.
             */
            "ff-dropdown": LocalJSX.IntrinsicElements["ff-dropdown"] & JSXBase.HTMLAttributes<HTMLFfDropdownElement>;
        }
    }
}
