import { useMemo, useState } from 'react';
import type { CSSProperties } from 'react';
/*
  FfButton / FfDropdown / FfDataTable / FfModal are React wrappers for the Stencil
  web components. They are auto-generated by @stencil/react-output-target and contain
  zero styling logic. Every component's runtime lives in packages/components/src/components/*.
  Visual identity arrives exclusively through the CSS imports in main.tsx
  (contract.css + brand pack), via the token cascade described in the monorepo README.
*/
import { FfButton, FfDropdown, FfDataTable, FfModal } from '@fuggetlenfe/react-wrapper';
import './App.css';

type ThemeMode = 'light' | 'dark';

type ThemeToggleOption = {
  label: string;
  value: ThemeMode;
};

/*
  CssTokenOverrides: Intersection type that extends CSSProperties with --ff-* custom property keys.
  This allows passing token overrides as inline styles without using `as CSSProperties` type assertions.
  The --ff-button-* properties defined here override the values from contract.css and the brand pack
  for this specific component instance only.
*/
type CssTokenOverrides = CSSProperties & Record<`--ff-${string}`, string>;

const themeToggleOptions: readonly ThemeToggleOption[] = [
  { label: 'Light', value: 'light' },
  { label: 'Dark', value: 'dark' }
];

const brandTwoInlineTokenStyle: CssTokenOverrides = {
  '--ff-button-padding-inline': '8px',
  '--ff-button-padding-block': '2px',
  '--ff-button-radius': '6px'
};

const variantInlineTokenStyle: CssTokenOverrides = {
  '--ff-button-padding-inline': '0.95rem',
  '--ff-button-padding-block': '0.48rem',
  '--ff-button-radius': '4px'
};

/*
  Static sample data for the data table demo. Kept static (not fetched) so the SSG
  prerender step emits byte-identical HTML in Node and in the browser, and the hydration
  step has zero mismatches. In a real app this would come from a server loader.
*/
const tableColumns = [
  { key: 'name', label: 'Customer', width: '2fr' },
  { key: 'plan', label: 'Plan', width: '1fr' },
  { key: 'seats', label: 'Seats', width: '0.6fr', align: 'end' as const },
  { key: 'mrr', label: 'MRR', width: '0.8fr', align: 'end' as const },
  { key: 'active', label: 'Active', width: '0.5fr', align: 'center' as const }
];

const tableRows = [
  { id: 'c-1', name: 'Aurora Partners', plan: 'Enterprise', seats: 420, mrr: '€ 18 400', active: true },
  { id: 'c-2', name: 'Northwind Labs', plan: 'Growth', seats: 84, mrr: '€ 3 960', active: true },
  { id: 'c-3', name: 'Helix Cooperative', plan: 'Growth', seats: 61, mrr: '€ 2 820', active: false },
  { id: 'c-4', name: 'Lumen & Stone', plan: 'Starter', seats: 12, mrr: '€ 480', active: true },
  { id: 'c-5', name: 'Portside Logistics', plan: 'Enterprise', seats: 310, mrr: '€ 12 600', active: true }
];

const dropdownOptions = [
  { value: 'qtr', label: 'This quarter' },
  { value: 'hly', label: 'Half year' },
  { value: 'yr', label: 'Full year' },
  { value: 'all', label: 'All time', disabled: true }
];

function App() {
  const [activeTheme, setActiveTheme] = useState<ThemeMode>('light');
  const [period, setPeriod] = useState<string>('qtr');
  const [modalOpen, setModalOpen] = useState(false);

  const memoisedColumns = useMemo(() => tableColumns, []);
  const memoisedRows = useMemo(() => tableRows, []);

  /*
    data-brand and data-theme on the shell element activate the brand pack CSS.
    The brand pack overrides --ff-button-* variables via [data-brand][data-theme] selectors.
    Every Ff* component inside this shell inherits the Brand 2 visual identity automatically.
  */
  return (
    <main className="consumer-shell" data-brand="brand-2" data-theme={activeTheme}>
      <section className="hero-card">
        <p className="eyebrow">React app · external CSS brand pack</p>
        <h1>React consumes only the wrapper logic, then receives Brand 2 from Figma-based CSS.</h1>
        <p className="body-copy">
          This app imports the compiled React wrapper plus the Brand 2 light and dark packs that
          follow the Figma token set. Brand and theme live on the outer shell, so the Stencil
          primitive stays visually neutral until the external stylesheet is present.
        </p>

        <div className="theme-bar" role="group" aria-label="Theme switcher">
          <p className="theme-label">Theme pack</p>
          <div className="theme-actions">
            {themeToggleOptions.map((themeToggleOption) => (
              <button
                key={themeToggleOption.value}
                type="button"
                className="theme-button"
                data-selected={activeTheme === themeToggleOption.value}
                onClick={() => setActiveTheme(themeToggleOption.value)}
              >
                {themeToggleOption.label}
              </button>
            ))}
          </div>
        </div>

        <div className="button-row">
          <FfButton className="brand-host">Brand 2 default</FfButton>
          <FfButton className="pill-host">Class-based override</FfButton>
          <FfButton style={brandTwoInlineTokenStyle}>Inline token tweak</FfButton>
        </div>
      </section>

      <section className="variants-section">
        <p className="eyebrow">All variants</p>
        <h2 className="section-title">Component API</h2>
        <div className="variants-grid">
          <div className="variant-item">
            <FfButton>Default</FfButton>
            <span className="variant-label">Default button</span>
          </div>
          <div className="variant-item">
            <FfButton disabled>Disabled</FfButton>
            <span className="variant-label">Disabled state</span>
          </div>
          <div className="variant-item">
            <FfButton fullWidth>Full width</FfButton>
            <span className="variant-label">Full-width layout</span>
          </div>
          <div className="variant-item">
            <FfButton type="submit">Submit</FfButton>
            <span className="variant-label">Type: submit</span>
          </div>
          <div className="variant-item">
            <FfButton type="reset">Reset</FfButton>
            <span className="variant-label">Type: reset</span>
          </div>
          <div className="variant-item">
            <FfButton className="pill-host">Pill shape</FfButton>
            <span className="variant-label">Class override (border-radius: 999px)</span>
          </div>
          <div className="variant-item">
            <FfButton style={variantInlineTokenStyle}>Custom tokens</FfButton>
            <span className="variant-label">Inline token override</span>
          </div>
          <div className="variant-item">
            <FfButton>{'\u2192 Next'}</FfButton>
            <span className="variant-label">Slotted icon text</span>
          </div>
        </div>
      </section>

      <section className="variants-section">
        <p className="eyebrow">SSR-safe primitives</p>
        <h2 className="section-title">Dropdown, Data table, Modal</h2>
        <p className="body-copy">
          These three primitives are written with the same framework-independent contract as
          the button: pure render, no DOM access in lifecycle constructors, open/close state
          controlled through props, and all visual values resolved through the token cascade.
          That means this entire page is pre-rendered at build time through the Stencil
          hydrate module and arrives as Declarative Shadow DOM — no layout shift on hydration.
        </p>

        <div className="button-row">
          <FfDropdown
            options={dropdownOptions}
            value={period}
            placeholder="Select reporting period"
            ffAriaLabel="Reporting period"
            onFfChange={(event) => setPeriod(event.detail.value)}
          />
          <FfButton variant="primary" onFfClick={() => setModalOpen(true)}>
            Open confirmation modal
          </FfButton>
        </div>

        <div style={{ marginTop: '1.25rem' }}>
          <FfDataTable
            columns={memoisedColumns}
            rows={memoisedRows}
            sortable
            selectionMode="multiple"
            ffCaption="Top customers by MRR"
          />
        </div>

        <FfModal
          open={modalOpen}
          ffTitle="Confirm export"
          onFfClose={() => setModalOpen(false)}
        >
          <p>
            The selected customers will be exported as a signed CSV. This action is audited
            and cannot be undone from the reporting UI.
          </p>
          <div slot="footer" style={{ display: 'flex', gap: '0.5rem' }}>
            <FfButton variant="ghost" onFfClick={() => setModalOpen(false)}>
              Cancel
            </FfButton>
            <FfButton variant="primary" onFfClick={() => setModalOpen(false)}>
              Export
            </FfButton>
          </div>
        </FfModal>
      </section>

      <section className="info-grid">
        <article className="info-card">
          <p className="eyebrow">Consumer imports</p>
          <div className="detail-block" aria-label="Consumer imports">
            <div className="detail-line">Import the React wrapper package.</div>
            <div className="detail-line">Import the shared token contract.</div>
            <div className="detail-line">Import the Brand 2 light stylesheet.</div>
            <div className="detail-line">Import the Brand 2 dark stylesheet.</div>
            <div className="detail-line detail-line--gap">
              Set <span>data-brand="brand-2"</span> and the active theme on the outer shell.
            </div>
            <div className="detail-line">Render the same FfButton logic inside that shell.</div>
          </div>
        </article>

        <article className="info-card">
          <p className="eyebrow">Theme behavior</p>
          <div className="detail-block" aria-label="Theme behavior">
            <div className="detail-line">Light and dark are swapped only by the shell.</div>
            <div className="detail-line">The button keeps the same logic API in both modes.</div>
            <div className="detail-line">Brand 2 colors come from the Figma-derived CSS pack.</div>
            <div className="detail-line">
              The current PoC stays intentionally narrow: only the button exists in Figma and ships.
            </div>
          </div>
        </article>

        <article className="info-card">
          <p className="eyebrow">What proves the separation</p>
          <div className="proof-list">
            <div className="proof-item">The wrapper package provides framework integration only.</div>
            <div className="proof-item">
              The primitives styling appears only after the brand CSS is imported.
            </div>
            <div className="proof-item">
              The shared components still accept custom classes and per-instance CSS properties.
            </div>
            <div className="proof-item">
              Removing a non-Figma primitive does not change the wrapper contract for the button.
            </div>
          </div>
        </article>
      </section>
    </main>
  );
}

export default App;
